`no` int(11) unsigned NOT NULL AUTO_INCREMENT,
`first_order_no` int(11) unsigned NOT NULL,
`app_home_image` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`pc_home_image` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`home_title` varchar(100) COLLATE utf8_bin DEFAULT NULL,
`home_subtitle` varchar(100) COLLATE utf8_bin DEFAULT NULL,
`home_box_color` varchar(7) COLLATE utf8_bin DEFAULT NULL,
`home_bg_color` varchar(7) COLLATE utf8_bin DEFAULT NULL,
`display_price` tinyint(1) unsigned DEFAULT NULL,
`article_floating_title` varchar(50) COLLATE utf8_bin DEFAULT NULL,
`display_app_article_floating` tinyint(1) unsigned DEFAULT NULL,
`app_section_title` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`app_section_subtitle` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`app_section_sentence` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`app_section_image` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`app_section_subimage` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`pc_section_title` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`pc_section_subtitle` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`pc_section_sentence` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`pc_section_image` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`pc_section_subimage` varchar(300) COLLATE utf8_bin DEFAULT NULL,
`create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
`update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,